import type {
  UserProfile,
  UserRequest,
  WalletTransaction,
  Notification,
} from '@/types/user';

export const mockUser: UserProfile = {
  id:              'u-001',
  name:            'Sara Ahmed',
  email:           'sara@commuter.eg',
  phone:           '01098765432',
  gender:          'female',
  date_of_birth:   '1998-03-22',
  avatar_url:      null,
  joined_at:       '2025-01-10',
  rating:          4.6,
  total_cycles:    48,
  active_cycles:   2,
  wallet_balance:  320,
  gender_pref:     'mixed',
  walk_minutes:    0,
  saved_locations: [
    {
      id:      'sl-1',
      label:   'home',
      name:    'Home',
      address: '15 El-Nasr St, Nasr City, Cairo',
      lat:     30.0626,
      lng:     31.3417,
    },
    {
      id:      'sl-2',
      label:   'work',
      name:    'Office',
      address: 'Smart Village, 6 October City',
      lat:     30.0710,
      lng:     30.9937,
    },
  ],
};

export const mockRequests: UserRequest[] = [
  {
    id:                  'req-001',
    status:              'price_raised',
    origin:              { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
    destination:         { address: 'Smart Village, 6 Oct', lat: 30.0710, lng: 30.9937 },
    distance_km:         24.5,
    duration_minutes:    35,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'front-passenger', label: 'Front seat (Passenger side)', type: 'front', extra_cost_egp: 10 },
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:55',
    departure_to:        '08:55',
    cycle_start_date:    '2026-05-05',
    cycle_end_date:      '2026-05-11',
    base_price:          75,
    estimated_price_min: 360,
    estimated_price_max: 490,
    offered_price:       95,
    passenger_count:     1,
    pickup_points:       [{ passenger_id: 'u-001', passenger_name: 'Sara Ahmed', passenger_gender: 'female', lat: 30.0626, lng: 31.3417, address: 'Nasr City, Cairo', pickup_time_offset: 0 }],
    driver_id:           'd-001',
    driver_name:         'Ahmed Hassan',
    driver_rating:       4.8,
    co_passengers:       [
      { id: 'p-001', first_name: 'Nour', gender: 'female' },
      { id: 'p-002', first_name: 'Karim', gender: 'male' },
    ],
    created_at:          '2026-04-25T10:00:00Z',
  },
  {
    id:                   'req-002',
    status:               'active',
    origin:               { address: 'Heliopolis, Cairo', lat: 30.0897, lng: 31.3222 },
    destination:          { address: 'Maadi, Cairo', lat: 29.9602, lng: 31.2569 },
    distance_km:          18.2,
    duration_minutes:     28,
    trip_type:              'round_trip',
    ride_type:              'shared',
    gender_pref:            'same',
    seat_preference:        'any',
    walk_minutes:           5,
    days:                   ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:           '08:00',
    arrival_to:             '09:00',
    departure_from:         '07:32',
    departure_to:           '08:32',
    return_arrival_from:    '17:30',
    return_arrival_to:      '18:30',
    return_departure_from:  '17:02',
    return_departure_to:    '18:02',
    cycle_start_date:     '2026-04-27',
    cycle_end_date:       '2026-05-03',
    base_price:           65,
    estimated_price_min:  280,
    estimated_price_max:  380,
    passenger_count:      1,
    pickup_points:        [{ passenger_id: 'u-001', passenger_name: 'Sara Ahmed', passenger_gender: 'female', lat: 30.0897, lng: 31.3222, address: 'Heliopolis, Cairo', pickup_time_offset: 0 }],
    driver_id:            'd-002',
    driver_name:          'Mohamed Samir',
    driver_rating:        4.5,
    co_passengers:        [{ id: 'p-003', first_name: 'Sara', gender: 'female' }],
    created_at:           '2026-04-20T08:30:00Z',
  },
  {
    id:                  'req-003',
    status:              'submitted',
    origin:              { address: '6 October City', lat: 29.9730, lng: 30.9269 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         31.8,
    duration_minutes:    45,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'rear-right', label: 'Rear seat (Right / Window)', type: 'rear-window', extra_cost_egp: 8 },
    walk_minutes:        10,
    days:                ['Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '07:30',
    arrival_to:          '08:30',
    departure_from:      '06:45',
    departure_to:        '07:45',
    cycle_start_date:    '2026-05-12',
    cycle_end_date:      '2026-05-18',
    base_price:          0,
    estimated_price_min: 490,
    estimated_price_max: 660,
    passenger_count:     1,
    pickup_points:       [{ passenger_id: 'u-001', passenger_name: 'Sara Ahmed', passenger_gender: 'female', lat: 29.9730, lng: 30.9269, address: '6 October City', pickup_time_offset: 0 }],
    created_at:          '2026-04-27T14:00:00Z',
  },
  {
    id:                  'req-004',
    status:              'completed',
    origin:              { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
    destination:         { address: 'Maadi, Cairo', lat: 29.9602, lng: 31.2569 },
    distance_km:         22.1,
    duration_minutes:    32,
    trip_type:           'one_way',
    ride_type:           'private',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:00',
    arrival_to:          '09:00',
    departure_from:      '07:28',
    departure_to:        '08:28',
    cycle_start_date:    '2026-04-14',
    cycle_end_date:      '2026-04-20',
    base_price:          70,
    estimated_price_min: 680,
    estimated_price_max: 920,
    passenger_count:     1,
    pickup_points:       [{ passenger_id: 'u-001', passenger_name: 'Sara Ahmed', passenger_gender: 'female', lat: 30.0626, lng: 31.3417, address: 'Nasr City, Cairo', pickup_time_offset: 0 }],
    driver_id:           'd-001',
    driver_name:         'Ahmed Hassan',
    driver_rating:       4.8,
    co_passengers:       [{ id: 'p-004', first_name: 'Omar', gender: 'male' }],
    created_at:          '2026-04-10T09:00:00Z',
  },
];

export const mockTransactions: WalletTransaction[] = [
  {
    id: 't-1',
    type: 'top_up',
    amount: 200,
    description: 'Wallet top-up',
    date: '2026-04-27',
    balance: 320,
  },
  {
    id: 't-2',
    type: 'payment',
    amount: -85,
    description: 'Maadi cycle payment',
    date: '2026-04-21',
    balance: 120,
  },
  {
    id: 't-3',
    type: 'refund',
    amount: 5,
    description: 'Overpayment refund',
    date: '2026-04-14',
    balance: 205,
  },
  {
    id: 't-4',
    type: 'top_up',
    amount: 200,
    description: 'Wallet top-up',
    date: '2026-04-01',
    balance: 200,
  },
  {
    id: 't-5',
    type: 'payment',
    amount: -70,
    description: 'Nasr City–Maadi cycle payment',
    date: '2026-03-24',
    balance: 130,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n-1',
    type: 'price_raised',
    isRead: false,
    title: 'Price updated for your ride',
    body: 'Driver offered EGP 95/week (was EGP 75) for Nasr City → Smart Village.',
    createdAt: '2026-04-27T12:00:00Z',
    actionUrl: '/user/my-requests',
  },
  {
    id: 'n-2',
    type: 'request_matched',
    isRead: false,
    title: 'Driver matched!',
    body: 'Ahmed H. accepted your Maadi request.',
    createdAt: '2026-04-26T09:00:00Z',
    actionUrl: '/user/my-requests',
  },
  {
    id: 'n-3',
    type: 'cycle_starting_tomorrow',
    isRead: true,
    title: 'Your cycle starts tomorrow',
    body: 'Pickup at 8:00 AM from Heliopolis.',
    createdAt: '2026-04-26T18:00:00Z',
  },
  {
    id: 'n-4',
    type: 'payment_deducted',
    isRead: true,
    title: 'Payment deducted',
    body: 'EGP 85 deducted for Maadi cycle (Apr 21–27).',
    createdAt: '2026-04-21T08:00:00Z',
  },
  {
    id: 'n-5',
    type: 'cycle_completed',
    isRead: true,
    title: 'Cycle completed',
    body: 'Your Nasr City → Maadi cycle (Apr 14–20) is done. Rate your driver!',
    createdAt: '2026-04-20T20:00:00Z',
    actionUrl: '/user/rate/req-004',
  },
];
