import { DriverCycleRequest, DriverProfile } from '@/types/driver';
import type { TimeSlot } from '@/types/shared';

// ── Helper — build a mock TimeSlot from flat request fields ──────────────────

function makeSlot(
  id: string,
  req: {
    trip_type: 'one_way' | 'round_trip';
    origin: { address: string; lat: number; lng: number };
    destination: { address: string; lat: number; lng: number };
    distance_km: number;
    duration_minutes: number;
    days: string[];
    departure_from: string;
    departure_to: string;
    arrival_from?: string;
    arrival_to?: string;
    return_departure_from?: string;
    return_departure_to?: string;
    return_arrival_from?: string;
    return_arrival_to?: string;
  },
): TimeSlot {
  return {
    id,
    trip_type: req.trip_type,
    origin: req.origin,
    stops: [],
    destination: req.destination,
    route: {
      coordinates: [
        [req.origin.lng, req.origin.lat],
        [req.destination.lng, req.destination.lat],
      ],
      distance_km: req.distance_km,
      duration_minutes: req.duration_minutes,
      summary: `${req.origin.address} → ${req.destination.address}`,
    },
    route_set: true,
    return_origin: req.trip_type === 'round_trip' ? req.destination : null,
    return_destination: req.trip_type === 'round_trip' ? req.origin : null,
    return_route: req.trip_type === 'round_trip' ? {
      coordinates: [
        [req.destination.lng, req.destination.lat],
        [req.origin.lng, req.origin.lat],
      ],
      distance_km: req.distance_km,
      duration_minutes: req.duration_minutes,
      summary: `${req.destination.address} → ${req.origin.address}`,
    } : null,
    return_customized: false,
    pickup_from: req.departure_from,
    pickup_to: req.departure_to,
    arrival_from: req.arrival_from ?? '',
    arrival_to: req.arrival_to ?? '',
    return_pickup_from: req.return_departure_from,
    return_pickup_to: req.return_departure_to,
    return_arrival_from: req.return_arrival_from,
    return_arrival_to: req.return_arrival_to,
    days: req.days as TimeSlot['days'],
  };
}

// ── Driver profile ────────────────────────────────────────────────────────────

export const mockDriver: DriverProfile = {
  id:                   'drv-001',
  name:                 'Ahmed Hassan',
  phone:                '+20 10 1234 5678',
  email:                'ahmed.hassan@example.com',
  address:              '15 El-Nasr St, Nasr City, Cairo',
  nationalId:           '29901011234567',
  drivingLicenseNumber: 'DL-123456',
  carLicensePlate:      'أ ب ج 1234',
  carModel:             'Toyota Corolla',
  carYear:              2019,
  carColor:             'White',
  rating:               4.8,
  totalTrips:           312,
  walletBalance:        1240.0,
  joinedAt:             '2024-01-15T08:00:00.000Z',
  isVerified:           true,
  completedCycles:      3,
  activeCycles:         2,
  gender:               'male',
  documents: {
    nationalIdFront: null,
    nationalIdBack:  null,
    drivingLicense:  null,
    carLicense:      null,
    criminalRecord:  null,
    profilePhoto:    null,
  },
};

// ── Mock requests ─────────────────────────────────────────────────────────────

export const mockRequests: DriverCycleRequest[] = [
  {
    // Pool — 3 passengers, mixed gender, front seat pref, 10-min walk
    id:                  'req-001',
    status:              'available',
    origin:              { address: 'Nasr City', lat: 30.0626, lng: 31.3417 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         24.5,
    duration_minutes:    45,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'front-passenger', label: 'Front seat (Passenger side)', type: 'front', extra_cost_egp: 10 },
    walk_minutes:        10,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:45',
    departure_to:        '08:45',
    cycle_start_date:    '2026-05-04',
    cycle_end_date:      '2026-05-10',
    base_price:          1800,
    estimated_price_min: 1600,
    estimated_price_max: 2100,
    passenger_count:     3,
    time_slots: [makeSlot('slot-req-001-1', {
      trip_type: 'one_way',
      origin: { address: 'Nasr City', lat: 30.0626, lng: 31.3417 },
      destination: { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
      distance_km: 24.5, duration_minutes: 45,
      days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
      departure_from: '07:45', departure_to: '08:45',
      arrival_from: '08:30', arrival_to: '09:30',
    })],
    pickup_points: [
      { passenger_id: 'p-001', passenger_name: 'Sara Khaled',  passenger_gender: 'female', lat: 30.0669, lng: 31.3278, address: '12 Abbas El-Akkad St, Nasr City', pickup_time_offset: 0 },
      { passenger_id: 'p-002', passenger_name: 'Mohamed Ali',  passenger_gender: 'male',   lat: 30.0612, lng: 31.3199, address: '5 Makram Ebeid St, Nasr City',      pickup_time_offset: 5 },
      { passenger_id: 'p-003', passenger_name: 'Heba Rashid',  passenger_gender: 'female', lat: 30.0640, lng: 31.3230, address: '8 Nasr City Main St, Nasr City',    pickup_time_offset: 8 },
    ],
    created_at:   '2026-04-24T10:00:00.000Z',
    group_type:   null,
    group_action: null,
  },

  {
    // Single — same gender, any seat, no walk, round trip
    id:                   'req-002',
    status:               'available',
    origin:               { address: 'Maadi', lat: 29.9602, lng: 31.2569 },
    destination:          { address: 'New Cairo (5th Settlement)', lat: 30.0099, lng: 31.4312 },
    distance_km:          32.1,
    duration_minutes:     55,
    trip_type:            'round_trip',
    ride_type:            'private',
    gender_pref:          'same',
    seat_preference:      'any',
    walk_minutes:         0,
    days:                 ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:         '08:00',
    arrival_to:           '09:00',
    departure_from:       '07:05',
    departure_to:         '08:05',
    return_arrival_from:  '17:30',
    return_arrival_to:    '18:30',
    return_departure_from:'16:35',
    return_departure_to:  '17:35',
    cycle_start_date:     '2026-05-05',
    cycle_end_date:       '2026-05-11',
    base_price:           2100,
    estimated_price_min:  1800,
    estimated_price_max:  2400,
    passenger_count:      1,
    time_slots: [makeSlot('slot-req-002-1', {
      trip_type: 'round_trip',
      origin: { address: 'Maadi', lat: 29.9602, lng: 31.2569 },
      destination: { address: 'New Cairo (5th Settlement)', lat: 30.0099, lng: 31.4312 },
      distance_km: 32.1, duration_minutes: 55,
      days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
      departure_from: '07:05', departure_to: '08:05',
      arrival_from: '08:00', arrival_to: '09:00',
      return_departure_from: '16:35', return_departure_to: '17:35',
      return_arrival_from: '17:30', return_arrival_to: '18:30',
    })],
    pickup_points: [
      { passenger_id: 'p-005', passenger_name: 'Amr Samir', passenger_gender: 'male', lat: 29.9602, lng: 31.2569, address: '17 Road 9, Maadi', pickup_time_offset: 0 },
    ],
    created_at:   '2026-04-22T09:00:00.000Z',
    group_type:   null,
    group_action: null,
  },

  {
    // Active cycle — currently running
    id:                  'req-003',
    status:              'active',
    origin:              { address: 'Heliopolis, Cairo', lat: 30.0897, lng: 31.3222 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         14.3,
    duration_minutes:    22,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        5,
    days:                ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '07:45',
    arrival_to:          '08:45',
    departure_from:      '07:23',
    departure_to:        '08:23',
    cycle_start_date:    '2026-05-05',
    cycle_end_date:      '2026-05-11',
    base_price:          1200,
    estimated_price_min: 900,
    estimated_price_max: 1200,
    passenger_count:     2,
    time_slots: [makeSlot('slot-req-003-1', {
      trip_type: 'one_way',
      origin: { address: 'Heliopolis, Cairo', lat: 30.0897, lng: 31.3222 },
      destination: { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
      distance_km: 14.3, duration_minutes: 22,
      days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      departure_from: '07:23', departure_to: '08:23',
      arrival_from: '07:45', arrival_to: '08:45',
    })],
    pickup_points: [
      { passenger_id: 'p-010', passenger_name: 'Fatima Khaled',  passenger_gender: 'female', lat: 30.0897, lng: 31.3222, address: '22 Ibrahim Abbass St, Heliopolis', pickup_time_offset: 0 },
      { passenger_id: 'p-011', passenger_name: 'Hassan Mohamed', passenger_gender: 'male',   lat: 30.0856, lng: 31.3189, address: '8 El-Merghani St, Heliopolis',      pickup_time_offset: 3 },
    ],
    created_at:   '2026-04-28T10:30:00.000Z',
    group_type:   null,
    group_action: null,
    cycle_days: [
      { date: '2026-05-05', pickup_time: '07:25', dropoff_time: '07:47', driver_name: 'Ahmed Hassan',  status: 'completed' },
      { date: '2026-05-06', pickup_time: '07:23', dropoff_time: '07:45', driver_name: 'Mohamed Samir', status: 'completed' },
      { date: '2026-05-07', pickup_time: '07:30', dropoff_time: '07:52', driver_name: 'Omar Khaled',   status: 'cancelled' },
      { date: '2026-05-08', pickup_time: '07:24', dropoff_time: '07:46', driver_name: 'Karim Youssef', status: 'completed' },
      { date: '2026-05-09', driver_name: 'Hassan Ibrahim', status: null },
    ],
  },

  {
    id:                  'req-004',
    status:              'confirmed',
    origin:              { address: 'New Cairo, Cairo', lat: 30.0228, lng: 31.4853 },
    destination:         { address: 'Smart Village, 6 October', lat: 30.0710, lng: 30.9937 },
    distance_km:         28.5,
    duration_minutes:    42,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'same',
    seat_preference:     { id: 'rear-right', label: 'Rear seat (Right / Window)', type: 'rear-window', extra_cost_egp: 8 },
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:48',
    departure_to:        '08:48',
    cycle_start_date:    '2026-05-12',
    cycle_end_date:      '2026-05-18',
    base_price:          1600,
    estimated_price_min: 1400,
    estimated_price_max: 1800,
    passenger_count:     1,
    time_slots: [makeSlot('slot-req-004-1', {
      trip_type: 'one_way',
      origin: { address: 'New Cairo, Cairo', lat: 30.0228, lng: 31.4853 },
      destination: { address: 'Smart Village, 6 October', lat: 30.0710, lng: 30.9937 },
      distance_km: 28.5, duration_minutes: 42,
      days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      departure_from: '07:48', departure_to: '08:48',
      arrival_from: '08:30', arrival_to: '09:30',
    })],
    pickup_points: [
      { passenger_id: 'p-012', passenger_name: 'Layla Noor', passenger_gender: 'female', lat: 30.0228, lng: 31.4853, address: '45 New Cairo Street, New Cairo', pickup_time_offset: 0 },
    ],
    created_at:   '2026-05-01T11:45:00.000Z',
    group_type:   null,
    group_action: null,
  },

  {
    // Completed cycle
    id:                  'req-005',
    status:              'completed',
    origin:              { address: 'Zamalek, Cairo', lat: 30.0719, lng: 31.2475 },
    destination:         { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
    distance_km:         16.8,
    duration_minutes:    25,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '09:30',
    arrival_to:          '10:30',
    departure_from:      '09:05',
    departure_to:        '10:05',
    cycle_start_date:    '2026-04-21',
    cycle_end_date:      '2026-04-27',
    base_price:          1350,
    estimated_price_min: 1050,
    estimated_price_max: 1400,
    passenger_count:     2,
    time_slots: [makeSlot('slot-req-005-1', {
      trip_type: 'one_way',
      origin: { address: 'Zamalek, Cairo', lat: 30.0719, lng: 31.2475 },
      destination: { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
      distance_km: 16.8, duration_minutes: 25,
      days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      departure_from: '09:05', departure_to: '10:05',
      arrival_from: '09:30', arrival_to: '10:30',
    })],
    pickup_points: [
      { passenger_id: 'p-013', passenger_name: 'Noor Ibrahim', passenger_gender: 'female', lat: 30.0719, lng: 31.2475, address: '3 Saray El-Gezira, Zamalek',      pickup_time_offset: 0 },
      { passenger_id: 'p-014', passenger_name: 'Karim Hassan', passenger_gender: 'male',   lat: 30.0686, lng: 31.2445, address: '12 26th of July St, Zamalek', pickup_time_offset: 4 },
    ],
    created_at:   '2026-04-15T08:00:00.000Z',
    group_type:   null,
    group_action: null,
    cycle_days: [
      { date: '2026-04-21', pickup_time: '09:07', dropoff_time: '09:32', driver_name: 'Tarek Mostafa',  status: 'completed' },
      { date: '2026-04-22', pickup_time: '09:05', dropoff_time: '09:30', driver_name: 'Ahmed Hassan',   status: 'completed' },
      { date: '2026-04-23', pickup_time: '09:10', dropoff_time: '09:35', driver_name: 'Mohamed Samir',  status: 'completed' },
      { date: '2026-04-24', driver_name: 'Omar Khaled',    status: null },
      { date: '2026-04-25', pickup_time: '09:06', dropoff_time: '09:31', driver_name: 'Karim Youssef',  status: 'completed' },
      { date: '2026-04-26', pickup_time: '09:08', dropoff_time: '09:33', driver_name: 'Hassan Ibrahim', status: 'completed' },
    ],
  },

  {
    id:                  'req-006',
    status:              'completed',
    origin:              { address: '6 October City', lat: 29.9730, lng: 30.9269 },
    destination:         { address: 'Giza, Cairo', lat: 30.0131, lng: 31.1898 },
    distance_km:         35.2,
    duration_minutes:    52,
    trip_type:           'one_way',
    ride_type:           'private',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        5,
    days:                ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '07:00',
    arrival_to:          '08:00',
    departure_from:      '06:08',
    departure_to:        '07:08',
    cycle_start_date:    '2026-04-07',
    cycle_end_date:      '2026-04-13',
    base_price:          2300,
    estimated_price_min: 2100,
    estimated_price_max: 2800,
    passenger_count:     1,
    time_slots: [makeSlot('slot-req-006-1', {
      trip_type: 'one_way',
      origin: { address: '6 October City', lat: 29.9730, lng: 30.9269 },
      destination: { address: 'Giza, Cairo', lat: 30.0131, lng: 31.1898 },
      distance_km: 35.2, duration_minutes: 52,
      days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      departure_from: '06:08', departure_to: '07:08',
      arrival_from: '07:00', arrival_to: '08:00',
    })],
    pickup_points: [
      { passenger_id: 'p-015', passenger_name: 'Youssef Ali', passenger_gender: 'male', lat: 29.9730, lng: 30.9269, address: '50 Mohammed Farid St, 6 October City', pickup_time_offset: 0 },
    ],
    created_at:   '2026-03-25T14:00:00.000Z',
    group_type:   null,
    group_action: null,
    cycle_days: [
      { date: '2026-04-07', pickup_time: '06:10', dropoff_time: '07:02', driver_name: 'Hassan Ibrahim', status: 'completed' },
      { date: '2026-04-08', pickup_time: '06:08', dropoff_time: '07:00', driver_name: 'Tarek Mostafa',  status: 'completed' },
      { date: '2026-04-09', pickup_time: '06:12', dropoff_time: '07:04', driver_name: 'Ahmed Hassan',   status: 'completed' },
      { date: '2026-04-10', driver_name: 'Mohamed Samir', status: 'cancelled' },
      { date: '2026-04-11', pickup_time: '06:09', dropoff_time: '07:01', driver_name: 'Omar Khaled',    status: 'completed' },
    ],
  },

  {
    id:                   'req-007',
    status:               'completed',
    origin:               { address: 'Helwan, Cairo', lat: 29.8589, lng: 31.3389 },
    destination:          { address: 'Maadi, Cairo', lat: 29.9602, lng: 31.2569 },
    distance_km:          18.5,
    duration_minutes:     28,
    trip_type:            'round_trip',
    ride_type:            'shared',
    gender_pref:          'same',
    seat_preference:      'any',
    walk_minutes:         10,
    days:                 ['Sat', 'Sun', 'Mon', 'Tue', 'Wed'],
    arrival_from:         '09:00',
    arrival_to:           '10:00',
    departure_from:       '08:32',
    departure_to:         '09:32',
    return_arrival_from:  '18:00',
    return_arrival_to:    '19:00',
    return_departure_from:'17:32',
    return_departure_to:  '18:32',
    cycle_start_date:     '2026-03-31',
    cycle_end_date:       '2026-04-06',
    base_price:           1500,
    estimated_price_min:  1200,
    estimated_price_max:  1600,
    passenger_count:      2,
    time_slots: [makeSlot('slot-req-007-1', {
      trip_type: 'round_trip',
      origin: { address: 'Helwan, Cairo', lat: 29.8589, lng: 31.3389 },
      destination: { address: 'Maadi, Cairo', lat: 29.9602, lng: 31.2569 },
      distance_km: 18.5, duration_minutes: 28,
      days: ['Sat', 'Sun', 'Mon', 'Tue', 'Wed'],
      departure_from: '08:32', departure_to: '09:32',
      arrival_from: '09:00', arrival_to: '10:00',
      return_departure_from: '17:32', return_departure_to: '18:32',
      return_arrival_from: '18:00', return_arrival_to: '19:00',
    })],
    pickup_points: [
      { passenger_id: 'p-016', passenger_name: 'Aisha Karim', passenger_gender: 'female', lat: 29.8589, lng: 31.3389, address: '15 Al-Ahram St, Helwan',  pickup_time_offset: 0 },
      { passenger_id: 'p-017', passenger_name: 'Dina Amira',  passenger_gender: 'female', lat: 29.8620, lng: 31.3420, address: '22 El-Safa St, Helwan',    pickup_time_offset: 2 },
    ],
    created_at:   '2026-03-18T09:30:00.000Z',
    group_type:   null,
    group_action: null,
    cycle_days: [
      { date: '2026-03-31', pickup_time: '08:34', dropoff_time: '09:02', driver_name: 'Karim Youssef',  status: 'completed' },
      { date: '2026-04-01', pickup_time: '08:32', dropoff_time: '09:00', driver_name: 'Hassan Ibrahim', status: 'completed' },
      { date: '2026-04-02', pickup_time: '08:35', dropoff_time: '09:03', driver_name: 'Tarek Mostafa',  status: 'cancelled' },
      { date: '2026-04-03', pickup_time: '08:31', dropoff_time: '08:59', driver_name: 'Ahmed Hassan',   status: 'completed' },
      { date: '2026-04-04', pickup_time: '08:33', dropoff_time: '09:01', driver_name: 'Mohamed Samir',  status: 'completed' },
    ],
  },

  {
    // Available — 3 passengers, waiting for driver to accept
    id:                  'req-008',
    status:              'available',
    origin:              { address: 'Shorouk, Cairo', lat: 30.1156, lng: 31.5553 },
    destination:         { address: 'Smart Village, 6 October', lat: 30.0710, lng: 30.9937 },
    distance_km:         42.3,
    duration_minutes:    62,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'front-passenger', label: 'Front seat (Passenger side)', type: 'front', extra_cost_egp: 10 },
    walk_minutes:        10,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:28',
    departure_to:        '08:28',
    cycle_start_date:    '2026-05-14',
    cycle_end_date:      '2026-05-20',
    base_price:          2500,
    estimated_price_min: 2300,
    estimated_price_max: 3000,
    passenger_count:     3,
    time_slots: [makeSlot('slot-req-008-1', {
      trip_type: 'one_way',
      origin: { address: 'Shorouk, Cairo', lat: 30.1156, lng: 31.5553 },
      destination: { address: 'Smart Village, 6 October', lat: 30.0710, lng: 30.9937 },
      distance_km: 42.3, duration_minutes: 62,
      days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
      departure_from: '07:28', departure_to: '08:28',
      arrival_from: '08:30', arrival_to: '09:30',
    })],
    pickup_points: [
      { passenger_id: 'p-018', passenger_name: 'Mona Hassan', passenger_gender: 'female', lat: 30.1156, lng: 31.5553, address: '8 Palm Hills, Shorouk',         pickup_time_offset: 0 },
      { passenger_id: 'p-019', passenger_name: 'Omar Khaled', passenger_gender: 'male',   lat: 30.1145, lng: 31.5530, address: '12 New Cairo Square, Shorouk',   pickup_time_offset: 3 },
      { passenger_id: 'p-030', passenger_name: 'Rana Sayed',  passenger_gender: 'female', lat: 30.1130, lng: 31.5515, address: '5 Shorouk Heights, Shorouk',     pickup_time_offset: 6 },
    ],
    created_at:   '2026-05-02T15:20:00.000Z',
    group_type:   null,
    group_action: null,
  },

  {
    // Confirmed — 3 passengers, starts soon
    id:                  'req-009',
    status:              'confirmed',
    origin:              { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
    destination:         { address: 'Smart Village, 6 Oct', lat: 30.0710, lng: 30.9937 },
    distance_km:         24.5,
    duration_minutes:    35,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'front-passenger', label: 'Front seat (Passenger side)', type: 'front', extra_cost_egp: 10 },
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:55',
    departure_to:        '08:55',
    cycle_start_date:    '2026-05-11',
    cycle_end_date:      '2026-05-17',
    cycle_id:            'cycle-001',
    today_trip_id:       'trip-today',
    base_price:          1800,
    estimated_price_min: 1600,
    estimated_price_max: 2100,
    passenger_count:     3,
    time_slots: [makeSlot('slot-req-009-1', {
      trip_type: 'one_way',
      origin: { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
      destination: { address: 'Smart Village, 6 Oct', lat: 30.0710, lng: 30.9937 },
      distance_km: 24.5, duration_minutes: 35,
      days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
      departure_from: '07:55', departure_to: '08:55',
      arrival_from: '08:30', arrival_to: '09:30',
    })],
    pickup_points: [
      { passenger_id: 'u-001', passenger_name: 'Sara Ahmed',   passenger_gender: 'female', lat: 30.0626, lng: 31.3417, address: '15 El-Nasr St, Nasr City',       pickup_time_offset: 0 },
      { passenger_id: 'u-002', passenger_name: 'Nour Magdy',   passenger_gender: 'female', lat: 30.0897, lng: 31.3222, address: '22 Hegaz St, Heliopolis',        pickup_time_offset: 15 },
      { passenger_id: 'u-003', passenger_name: 'Karim Nassif', passenger_gender: 'male',   lat: 30.0710, lng: 30.9937, address: 'Smart Village, 6 October',       pickup_time_offset: 30 },
    ],
    created_at:   '2026-05-05T07:00:00.000Z',
    group_type:   null,
    group_action: null,
  },

  {
    // Confirmed — currently running
    id:                  'req-010',
    status:              'confirmed',
    origin:              { address: 'Giza Plateau', lat: 30.0131, lng: 31.1898 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         18.2,
    duration_minutes:    28,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'same',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '07:30',
    arrival_to:          '08:30',
    departure_from:      '07:02',
    departure_to:        '08:02',
    cycle_start_date:    '2026-05-03',
    cycle_end_date:      '2026-05-09',
    base_price:          1400,
    estimated_price_min: 1200,
    estimated_price_max: 1600,
    passenger_count:     2,
    time_slots: [makeSlot('slot-req-010-1', {
      trip_type: 'one_way',
      origin: { address: 'Giza Plateau', lat: 30.0131, lng: 31.1898 },
      destination: { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
      distance_km: 18.2, duration_minutes: 28,
      days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
      departure_from: '07:02', departure_to: '08:02',
      arrival_from: '07:30', arrival_to: '08:30',
    })],
    pickup_points: [
      { passenger_id: 'p-022', passenger_name: 'Hana Saleh',  passenger_gender: 'female', lat: 30.0131, lng: 31.1898, address: '12 Giza Plateau Road, Giza', pickup_time_offset: 0 },
      { passenger_id: 'p-023', passenger_name: 'Leila Karim', passenger_gender: 'female', lat: 30.0150, lng: 31.1920, address: '5 Al-Ahram St, Giza',         pickup_time_offset: 2 },
    ],
    created_at:   '2026-05-05T06:30:00.000Z',
    group_type:   null,
    group_action: null,
  },

  {
    // Confirmed — pending start ~10 days
    id:                  'req-011',
    status:              'confirmed',
    origin:              { address: 'Zamalek, Cairo', lat: 30.0719, lng: 31.2475 },
    destination:         { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
    distance_km:         16.8,
    duration_minutes:    25,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '08:00',
    arrival_to:          '09:00',
    departure_from:      '07:35',
    departure_to:        '08:35',
    cycle_start_date:    '2026-05-16',
    cycle_end_date:      '2026-05-22',
    base_price:          1350,
    estimated_price_min: 1050,
    estimated_price_max: 1400,
    passenger_count:     2,
    time_slots: [makeSlot('slot-req-011-1', {
      trip_type: 'one_way',
      origin: { address: 'Zamalek, Cairo', lat: 30.0719, lng: 31.2475 },
      destination: { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
      distance_km: 16.8, duration_minutes: 25,
      days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      departure_from: '07:35', departure_to: '08:35',
      arrival_from: '08:00', arrival_to: '09:00',
    })],
    pickup_points: [
      { passenger_id: 'p-024', passenger_name: 'Ahmed Mansour', passenger_gender: 'male',   lat: 30.0719, lng: 31.2475, address: '3 Saray El-Gezira, Zamalek',   pickup_time_offset: 0 },
      { passenger_id: 'p-025', passenger_name: 'Rania Youssef', passenger_gender: 'female', lat: 30.0700, lng: 31.2450, address: '15 26th of July St, Zamalek',  pickup_time_offset: 3 },
    ],
    created_at:   '2026-05-03T12:00:00.000Z',
    group_type:   null,
    group_action: null,
  },

  {
    // Confirmed — round trip, pending start ~12 days
    id:                   'req-012',
    status:               'confirmed',
    origin:               { address: 'Heliopolis, Cairo', lat: 30.0897, lng: 31.3222 },
    destination:          { address: 'Maadi, Cairo', lat: 29.9602, lng: 31.2569 },
    distance_km:          18.2,
    duration_minutes:     28,
    trip_type:            'round_trip',
    ride_type:            'shared',
    gender_pref:          'same',
    seat_preference:      'any',
    walk_minutes:         5,
    days:                 ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:         '08:00',
    arrival_to:           '09:00',
    departure_from:       '07:32',
    departure_to:         '08:32',
    return_arrival_from:  '17:30',
    return_arrival_to:    '18:30',
    return_departure_from:'17:02',
    return_departure_to:  '18:02',
    cycle_start_date:     '2026-05-18',
    cycle_end_date:       '2026-05-24',
    base_price:           1650,
    estimated_price_min:  1400,
    estimated_price_max:  1800,
    passenger_count:      2,
    time_slots: [makeSlot('slot-req-012-1', {
      trip_type: 'round_trip',
      origin: { address: 'Heliopolis, Cairo', lat: 30.0897, lng: 31.3222 },
      destination: { address: 'Maadi, Cairo', lat: 29.9602, lng: 31.2569 },
      distance_km: 18.2, duration_minutes: 28,
      days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
      departure_from: '07:32', departure_to: '08:32',
      arrival_from: '08:00', arrival_to: '09:00',
      return_departure_from: '17:02', return_departure_to: '18:02',
      return_arrival_from: '17:30', return_arrival_to: '18:30',
    })],
    pickup_points: [
      { passenger_id: 'p-026', passenger_name: 'Farida Taha', passenger_gender: 'female', lat: 30.0897, lng: 31.3222, address: '22 Ibrahim Abbass St, Heliopolis', pickup_time_offset: 0 },
      { passenger_id: 'p-027', passenger_name: 'Zainab Noor', passenger_gender: 'female', lat: 30.0870, lng: 31.3195, address: '10 El-Merghani St, Heliopolis',    pickup_time_offset: 4 },
    ],
    created_at:   '2026-05-01T14:30:00.000Z',
    group_type:   null,
    group_action: null,
  },

  {
    // Confirmed — pending start ~9 days
    id:                  'req-013',
    status:              'confirmed',
    origin:              { address: 'New Cairo, Cairo', lat: 30.0228, lng: 31.4853 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         22.8,
    duration_minutes:    35,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Sat', 'Sun', 'Mon', 'Tue', 'Wed'],
    arrival_from:        '09:00',
    arrival_to:          '10:00',
    departure_from:      '08:25',
    departure_to:        '09:25',
    cycle_start_date:    '2026-05-15',
    cycle_end_date:      '2026-05-21',
    base_price:          1500,
    estimated_price_min: 1300,
    estimated_price_max: 1700,
    passenger_count:     2,
    time_slots: [makeSlot('slot-req-013-1', {
      trip_type: 'one_way',
      origin: { address: 'New Cairo, Cairo', lat: 30.0228, lng: 31.4853 },
      destination: { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
      distance_km: 22.8, duration_minutes: 35,
      days: ['Sat', 'Sun', 'Mon', 'Tue', 'Wed'],
      departure_from: '08:25', departure_to: '09:25',
      arrival_from: '09:00', arrival_to: '10:00',
    })],
    pickup_points: [
      { passenger_id: 'p-028', passenger_name: 'Maya Khalil', passenger_gender: 'female', lat: 30.0228, lng: 31.4853, address: '45 New Cairo Street, New Cairo', pickup_time_offset: 0 },
      { passenger_id: 'p-029', passenger_name: 'Tarek Eldin', passenger_gender: 'male',   lat: 30.0245, lng: 31.4875, address: '32 Al-Rehab St, New Cairo',       pickup_time_offset: 2 },
    ],
    created_at:   '2026-05-04T10:00:00.000Z',
    group_type:   null,
    group_action: null,
  },
];
