import { DriverCycleRequest, DriverProfile } from '@/types/driver';

export const mockDriver: DriverProfile = {
  id:                   'drv-001',
  name:                 'Ahmed Hassan',
  phone:                '+20 10 1234 5678',
  email:                'ahmed.hassan@example.com',
  address:              '15 El-Nasr St, Nasr City, Cairo',
  nationalId:           '29901011234567',
  drivingLicenseNumber: 'DL-123456',
  carLicensePlate:      'أ ب ج 1234',
  carModel:             'Toyota Corolla',
  carYear:              2019,
  carColor:             'White',
  rating:               4.8,
  totalTrips:           312,
  walletBalance:        1240.0,
  joinedAt:             '2024-01-15T08:00:00.000Z',
  isVerified:           true,
  completedCycles:      3,
  activeCycles:         2,
  gender:               'male',
  documents: {
    nationalIdFront: null,
    nationalIdBack:  null,
    drivingLicense:  null,
    carLicense:      null,
    criminalRecord:  null,
    profilePhoto:    null,
  },
};

export const mockRequests: DriverCycleRequest[] = [
  {
    // Pool request with 4 passengers — mixed gender, front seat pref, 10-min walk
    id:                  'req-001',
    status:              'available',
    origin:              { address: 'Nasr City', lat: 30.0626, lng: 31.3417 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         24.5,
    duration_minutes:    45,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'front-passenger', label: 'Front seat (Passenger side)', type: 'front', extra_cost_egp: 10 },
    walk_minutes:        10,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:45',
    departure_to:        '08:45',
    cycle_start_date:    '2026-05-04',
    cycle_end_date:      '2026-05-10',
    base_price:          1800,
    estimated_price_min: 1600,
    estimated_price_max: 2100,
    passenger_count:     4,
    pickup_points: [
      {
        passenger_id:       'p-001',
        passenger_name:     'Sara Khaled',
        passenger_gender:   'female',
        lat:                30.0669,
        lng:                31.3278,
        address:            '12 Abbas El-Akkad St, Nasr City',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-002',
        passenger_name:     'Mohamed Ali',
        passenger_gender:   'male',
        lat:                30.0612,
        lng:                31.3199,
        address:            '5 Makram Ebeid St, Nasr City',
        pickup_time_offset: 5,
      },
    ],
    created_at:          '2026-04-24T10:00:00.000Z',
  },
  {
    // Single request — same gender, any seat, no walk, round trip
    id:                  'req-002',
    status:              'available',
    origin:              { address: 'Maadi', lat: 29.9602, lng: 31.2569 },
    destination:         { address: 'New Cairo (5th Settlement)', lat: 30.0099, lng: 31.4312 },
    distance_km:         32.1,
    duration_minutes:    55,
    trip_type:              'round_trip',
    ride_type:              'private',
    gender_pref:            'same',
    seat_preference:        'any',
    walk_minutes:           0,
    days:                   ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:           '08:00',
    arrival_to:             '09:00',
    departure_from:         '07:05',
    departure_to:           '08:05',
    return_arrival_from:    '17:30',
    return_arrival_to:      '18:30',
    return_departure_from:  '16:35',
    return_departure_to:    '17:35',
    cycle_start_date:    '2026-05-05',
    cycle_end_date:      '2026-05-11',
    base_price:          2100,
    estimated_price_min: 1800,
    estimated_price_max: 2400,
    passenger_count:     1,
    pickup_points: [
      {
        passenger_id:       'p-005',
        passenger_name:     'Amr Samir',
        passenger_gender:   'male',
        lat:                29.9602,
        lng:                31.2569,
        address:            '17 Road 9, Maadi',
        pickup_time_offset: 0,
      },
    ],
    created_at:          '2026-04-22T09:00:00.000Z',
  },
];
