import { DriverCycleRequest, DriverProfile } from '@/types/driver';

export const mockDriver: DriverProfile = {
  id:                   'drv-001',
  name:                 'Ahmed Hassan',
  phone:                '+20 10 1234 5678',
  email:                'ahmed.hassan@example.com',
  address:              '15 El-Nasr St, Nasr City, Cairo',
  nationalId:           '29901011234567',
  drivingLicenseNumber: 'DL-123456',
  carLicensePlate:      'أ ب ج 1234',
  carModel:             'Toyota Corolla',
  carYear:              2019,
  carColor:             'White',
  rating:               4.8,
  totalTrips:           312,
  walletBalance:        1240.0,
  joinedAt:             '2024-01-15T08:00:00.000Z',
  isVerified:           true,
  completedCycles:      3,
  activeCycles:         2,
  gender:               'male',
  documents: {
    nationalIdFront: null,
    nationalIdBack:  null,
    drivingLicense:  null,
    carLicense:      null,
    criminalRecord:  null,
    profilePhoto:    null,
  },
};

export const mockRequests: DriverCycleRequest[] = [
  {
    // Pool request with 3 passengers — mixed gender, front seat pref, 10-min walk
    id:                  'req-001',
    status:              'available',
    origin:              { address: 'Nasr City', lat: 30.0626, lng: 31.3417 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         24.5,
    duration_minutes:    45,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'front-passenger', label: 'Front seat (Passenger side)', type: 'front', extra_cost_egp: 10 },
    walk_minutes:        10,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:45',
    departure_to:        '08:45',
    cycle_start_date:    '2026-05-04',
    cycle_end_date:      '2026-05-10',
    base_price:          1800,
    estimated_price_min: 1600,
    estimated_price_max: 2100,
    passenger_count:     3,
    pickup_points: [
      {
        passenger_id:       'p-001',
        passenger_name:     'Sara Khaled',
        passenger_gender:   'female',
        lat:                30.0669,
        lng:                31.3278,
        address:            '12 Abbas El-Akkad St, Nasr City',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-002',
        passenger_name:     'Mohamed Ali',
        passenger_gender:   'male',
        lat:                30.0612,
        lng:                31.3199,
        address:            '5 Makram Ebeid St, Nasr City',
        pickup_time_offset: 5,
      },
      {
        passenger_id:       'p-003',
        passenger_name:     'Heba Rashid',
        passenger_gender:   'female',
        lat:                30.0640,
        lng:                31.3230,
        address:            '8 Nasr City Main St, Nasr City',
        pickup_time_offset: 8,
      },
    ],
    created_at:          '2026-04-24T10:00:00.000Z',
  },
  {
    // Single request — same gender, any seat, no walk, round trip
    id:                  'req-002',
    status:              'available',
    origin:              { address: 'Maadi', lat: 29.9602, lng: 31.2569 },
    destination:         { address: 'New Cairo (5th Settlement)', lat: 30.0099, lng: 31.4312 },
    distance_km:         32.1,
    duration_minutes:    55,
    trip_type:              'round_trip',
    ride_type:              'private',
    gender_pref:            'same',
    seat_preference:        'any',
    walk_minutes:           0,
    days:                   ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:           '08:00',
    arrival_to:             '09:00',
    departure_from:         '07:05',
    departure_to:           '08:05',
    return_arrival_from:    '17:30',
    return_arrival_to:      '18:30',
    return_departure_from:  '16:35',
    return_departure_to:    '17:35',
    cycle_start_date:    '2026-05-05',
    cycle_end_date:      '2026-05-11',
    base_price:          2100,
    estimated_price_min: 1800,
    estimated_price_max: 2400,
    passenger_count:     1,
    pickup_points: [
      {
        passenger_id:       'p-005',
        passenger_name:     'Amr Samir',
        passenger_gender:   'male',
        lat:                29.9602,
        lng:                31.2569,
        address:            '17 Road 9, Maadi',
        pickup_time_offset: 0,
      },
    ],
    created_at:          '2026-04-22T09:00:00.000Z',
  },
  {
    // Active cycle - currently running
    id:                  'req-003',
    status:              'active',
    origin:              { address: 'Heliopolis, Cairo', lat: 30.0897, lng: 31.3222 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         14.3,
    duration_minutes:    22,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        5,
    days:                ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '07:45',
    arrival_to:          '08:45',
    departure_from:      '07:23',
    departure_to:        '08:23',
    cycle_start_date:    '2026-05-05',
    cycle_end_date:      '2026-05-11',
    base_price:          1200,
    estimated_price_min: 900,
    estimated_price_max: 1200,
    passenger_count:     2,
    pickup_points: [
      {
        passenger_id:       'p-010',
        passenger_name:     'Fatima Khaled',
        passenger_gender:   'female',
        lat:                30.0897,
        lng:                31.3222,
        address:            '22 Ibrahim Abbass St, Heliopolis',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-011',
        passenger_name:     'Hassan Mohamed',
        passenger_gender:   'male',
        lat:                30.0856,
        lng:                31.3189,
        address:            '8 El-Merghani St, Heliopolis',
        pickup_time_offset: 3,
      },
    ],
    created_at:          '2026-04-28T10:30:00.000Z',
  },
  {
    // Confirmed cycle - accepted but not yet active
    id:                  'req-004',
    status:              'confirmed',
    origin:              { address: 'New Cairo, Cairo', lat: 30.0228, lng: 31.4853 },
    destination:         { address: 'Smart Village, 6 October', lat: 30.0710, lng: 30.9937 },
    distance_km:         28.5,
    duration_minutes:    42,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'same',
    seat_preference:     { id: 'rear-right', label: 'Rear seat (Right / Window)', type: 'rear-window', extra_cost_egp: 8 },
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:48',
    departure_to:        '08:48',
    cycle_start_date:    '2026-05-12',
    cycle_end_date:      '2026-05-18',
    base_price:          1600,
    estimated_price_min: 1400,
    estimated_price_max: 1800,
    passenger_count:     1,
    pickup_points: [
      {
        passenger_id:       'p-012',
        passenger_name:     'Layla Noor',
        passenger_gender:   'female',
        lat:                30.0228,
        lng:                31.4853,
        address:            '45 New Cairo Street, New Cairo',
        pickup_time_offset: 0,
      },
    ],
    created_at:          '2026-05-01T11:45:00.000Z',
  },
  {
    // Completed cycle
    id:                  'req-005',
    status:              'completed',
    origin:              { address: 'Zamalek, Cairo', lat: 30.0719, lng: 31.2475 },
    destination:         { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
    distance_km:         16.8,
    duration_minutes:    25,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '09:30',
    arrival_to:          '10:30',
    departure_from:      '09:05',
    departure_to:        '10:05',
    cycle_start_date:    '2026-04-21',
    cycle_end_date:      '2026-04-27',
    base_price:          1350,
    estimated_price_min: 1050,
    estimated_price_max: 1400,
    passenger_count:     2,
    pickup_points: [
      {
        passenger_id:       'p-013',
        passenger_name:     'Noor Ibrahim',
        passenger_gender:   'female',
        lat:                30.0719,
        lng:                31.2475,
        address:            '3 Saray El-Gezira, Zamalek',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-014',
        passenger_name:     'Karim Hassan',
        passenger_gender:   'male',
        lat:                30.0686,
        lng:                31.2445,
        address:            '12 26th of July St, Zamalek',
        pickup_time_offset: 4,
      },
    ],
    created_at:          '2026-04-15T08:00:00.000Z',
  },
  {
    // Completed cycle
    id:                  'req-006',
    status:              'completed',
    origin:              { address: '6 October City', lat: 29.9730, lng: 30.9269 },
    destination:         { address: 'Giza, Cairo', lat: 30.0131, lng: 31.1898 },
    distance_km:         35.2,
    duration_minutes:    52,
    trip_type:           'one_way',
    ride_type:           'private',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        5,
    days:                ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '07:00',
    arrival_to:          '08:00',
    departure_from:      '06:08',
    departure_to:        '07:08',
    cycle_start_date:    '2026-04-07',
    cycle_end_date:      '2026-04-13',
    base_price:          2300,
    estimated_price_min: 2100,
    estimated_price_max: 2800,
    passenger_count:     1,
    pickup_points: [
      {
        passenger_id:       'p-015',
        passenger_name:     'Youssef Ali',
        passenger_gender:   'male',
        lat:                29.9730,
        lng:                30.9269,
        address:            '50 Mohammed Farid St, 6 October City',
        pickup_time_offset: 0,
      },
    ],
    created_at:          '2026-03-25T14:00:00.000Z',
  },
  {
    // Completed cycle
    id:                  'req-007',
    status:              'completed',
    origin:              { address: 'Helwan, Cairo', lat: 29.8589, lng: 31.3389 },
    destination:         { address: 'Maadi, Cairo', lat: 29.9602, lng: 31.2569 },
    distance_km:         18.5,
    duration_minutes:    28,
    trip_type:           'round_trip',
    ride_type:           'shared',
    gender_pref:         'same',
    seat_preference:     'any',
    walk_minutes:        10,
    days:                ['Sat', 'Sun', 'Mon', 'Tue', 'Wed'],
    arrival_from:        '09:00',
    arrival_to:          '10:00',
    departure_from:      '08:32',
    departure_to:        '09:32',
    return_arrival_from: '18:00',
    return_arrival_to:   '19:00',
    return_departure_from: '17:32',
    return_departure_to: '18:32',
    cycle_start_date:    '2026-03-31',
    cycle_end_date:      '2026-04-06',
    base_price:          1500,
    estimated_price_min: 1200,
    estimated_price_max: 1600,
    passenger_count:     2,
    pickup_points: [
      {
        passenger_id:       'p-016',
        passenger_name:     'Aisha Karim',
        passenger_gender:   'female',
        lat:                29.8589,
        lng:                31.3389,
        address:            '15 Al-Ahram St, Helwan',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-017',
        passenger_name:     'Dina Amira',
        passenger_gender:   'female',
        lat:                29.8620,
        lng:                31.3420,
        address:            '22 El-Safa St, Helwan',
        pickup_time_offset: 2,
      },
    ],
    created_at:          '2026-03-18T09:30:00.000Z',
  },
  {
    // Available - waiting for driver to accept (3 passengers)
    id:                  'req-008',
    status:              'available',
    origin:              { address: 'Shorouk, Cairo', lat: 30.1156, lng: 31.5553 },
    destination:         { address: 'Smart Village, 6 October', lat: 30.0710, lng: 30.9937 },
    distance_km:         42.3,
    duration_minutes:    62,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'front-passenger', label: 'Front seat (Passenger side)', type: 'front', extra_cost_egp: 10 },
    walk_minutes:        10,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:28',
    departure_to:        '08:28',
    cycle_start_date:    '2026-05-14',
    cycle_end_date:      '2026-05-20',
    base_price:          2500,
    estimated_price_min: 2300,
    estimated_price_max: 3000,
    passenger_count:     3,
    pickup_points: [
      {
        passenger_id:       'p-018',
        passenger_name:     'Mona Hassan',
        passenger_gender:   'female',
        lat:                30.1156,
        lng:                31.5553,
        address:            '8 Palm Hills, Shorouk',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-019',
        passenger_name:     'Omar Khaled',
        passenger_gender:   'male',
        lat:                30.1145,
        lng:                31.5530,
        address:            '12 New Cairo Square, Shorouk',
        pickup_time_offset: 3,
      },
      {
        passenger_id:       'p-030',
        passenger_name:     'Rana Sayed',
        passenger_gender:   'female',
        lat:                30.1130,
        lng:                31.5515,
        address:            '5 Shorouk Heights, Shorouk',
        pickup_time_offset: 6,
      },
    ],
    created_at:          '2026-05-02T15:20:00.000Z',
  },
  {
    // Active - currently running (Currently tab - 3 passengers)
    id:                  'req-009',
    status:              'confirmed',
    origin:              { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
    destination:         { address: 'Smart Village, 6 Oct', lat: 30.0710, lng: 30.9937 },
    distance_km:         24.5,
    duration_minutes:    35,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     { id: 'front-passenger', label: 'Front seat (Passenger side)', type: 'front', extra_cost_egp: 10 },
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:30',
    arrival_to:          '09:30',
    departure_from:      '07:55',
    departure_to:        '08:55',
    cycle_start_date:    '2026-05-04',
    cycle_end_date:      '2026-05-10',
    base_price:          1800,
    estimated_price_min: 1600,
    estimated_price_max: 2100,
    passenger_count:     3,
    pickup_points: [
      {
        passenger_id:       'p-020',
        passenger_name:     'Sara Ahmed',
        passenger_gender:   'female',
        lat:                30.0626,
        lng:                31.3417,
        address:            'Nasr City, Cairo',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-021',
        passenger_name:     'Nour Magdy',
        passenger_gender:   'female',
        lat:                30.0650,
        lng:                31.3380,
        address:            '8 Abbas El-Akkad St, Nasr City',
        pickup_time_offset: 3,
      },
      {
        passenger_id:       'p-031',
        passenger_name:     'Karim Nassif',
        passenger_gender:   'male',
        lat:                30.0635,
        lng:                31.3400,
        address:            '15 Korba St, Nasr City',
        pickup_time_offset: 5,
      },
    ],
    created_at:          '2026-05-05T07:00:00.000Z',
  },
  {
    // Active - currently running (Currently tab)
    id:                  'req-010',
    status:              'confirmed',
    origin:              { address: 'Giza Plateau', lat: 30.0131, lng: 31.1898 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         18.2,
    duration_minutes:    28,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'same',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '07:30',
    arrival_to:          '08:30',
    departure_from:      '07:02',
    departure_to:        '08:02',
    cycle_start_date:    '2026-05-03',
    cycle_end_date:      '2026-05-09',
    base_price:          1400,
    estimated_price_min: 1200,
    estimated_price_max: 1600,
    passenger_count:     2,
    pickup_points: [
      {
        passenger_id:       'p-022',
        passenger_name:     'Hana Saleh',
        passenger_gender:   'female',
        lat:                30.0131,
        lng:                31.1898,
        address:            '12 Giza Plateau Road, Giza',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-023',
        passenger_name:     'Leila Karim',
        passenger_gender:   'female',
        lat:                30.0150,
        lng:                31.1920,
        address:            '5 Al-Ahram St, Giza',
        pickup_time_offset: 2,
      },
    ],
    created_at:          '2026-05-05T06:30:00.000Z',
  },
  {
    // Confirmed - waiting to start in ~10 days (Pending tab)
    id:                  'req-011',
    status:              'confirmed',
    origin:              { address: 'Zamalek, Cairo', lat: 30.0719, lng: 31.2475 },
    destination:         { address: 'Nasr City, Cairo', lat: 30.0626, lng: 31.3417 },
    distance_km:         16.8,
    duration_minutes:    25,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    arrival_from:        '08:00',
    arrival_to:          '09:00',
    departure_from:      '07:35',
    departure_to:        '08:35',
    cycle_start_date:    '2026-05-16',
    cycle_end_date:      '2026-05-22',
    base_price:          1350,
    estimated_price_min: 1050,
    estimated_price_max: 1400,
    passenger_count:     2,
    pickup_points: [
      {
        passenger_id:       'p-024',
        passenger_name:     'Ahmed Mansour',
        passenger_gender:   'male',
        lat:                30.0719,
        lng:                31.2475,
        address:            '3 Saray El-Gezira, Zamalek',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-025',
        passenger_name:     'Rania Youssef',
        passenger_gender:   'female',
        lat:                30.0700,
        lng:                31.2450,
        address:            '15 26th of July St, Zamalek',
        pickup_time_offset: 3,
      },
    ],
    created_at:          '2026-05-03T12:00:00.000Z',
  },
  {
    // Confirmed - waiting to start in ~12 days (Pending tab)
    id:                  'req-012',
    status:              'confirmed',
    origin:              { address: 'Heliopolis, Cairo', lat: 30.0897, lng: 31.3222 },
    destination:         { address: 'Maadi, Cairo', lat: 29.9602, lng: 31.2569 },
    distance_km:         18.2,
    duration_minutes:    28,
    trip_type:           'round_trip',
    ride_type:           'shared',
    gender_pref:         'same',
    seat_preference:     'any',
    walk_minutes:        5,
    days:                ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    arrival_from:        '08:00',
    arrival_to:          '09:00',
    departure_from:      '07:32',
    departure_to:        '08:32',
    return_arrival_from: '17:30',
    return_arrival_to:   '18:30',
    return_departure_from: '17:02',
    return_departure_to: '18:02',
    cycle_start_date:    '2026-05-18',
    cycle_end_date:      '2026-05-24',
    base_price:          1650,
    estimated_price_min: 1400,
    estimated_price_max: 1800,
    passenger_count:     2,
    pickup_points: [
      {
        passenger_id:       'p-026',
        passenger_name:     'Farida Taha',
        passenger_gender:   'female',
        lat:                30.0897,
        lng:                31.3222,
        address:            '22 Ibrahim Abbass St, Heliopolis',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-027',
        passenger_name:     'Zainab Noor',
        passenger_gender:   'female',
        lat:                30.0870,
        lng:                31.3195,
        address:            '10 El-Merghani St, Heliopolis',
        pickup_time_offset: 4,
      },
    ],
    created_at:          '2026-05-01T14:30:00.000Z',
  },
  {
    // Confirmed - waiting to start in ~9 days (Pending tab)
    id:                  'req-013',
    status:              'confirmed',
    origin:              { address: 'New Cairo, Cairo', lat: 30.0228, lng: 31.4853 },
    destination:         { address: 'Downtown Cairo', lat: 30.0444, lng: 31.2357 },
    distance_km:         22.8,
    duration_minutes:    35,
    trip_type:           'one_way',
    ride_type:           'shared',
    gender_pref:         'mixed',
    seat_preference:     'any',
    walk_minutes:        0,
    days:                ['Sat', 'Sun', 'Mon', 'Tue', 'Wed'],
    arrival_from:        '09:00',
    arrival_to:          '10:00',
    departure_from:      '08:25',
    departure_to:        '09:25',
    cycle_start_date:    '2026-05-15',
    cycle_end_date:      '2026-05-21',
    base_price:          1500,
    estimated_price_min: 1300,
    estimated_price_max: 1700,
    passenger_count:     2,
    pickup_points: [
      {
        passenger_id:       'p-028',
        passenger_name:     'Maya Khalil',
        passenger_gender:   'female',
        lat:                30.0228,
        lng:                31.4853,
        address:            '45 New Cairo Street, New Cairo',
        pickup_time_offset: 0,
      },
      {
        passenger_id:       'p-029',
        passenger_name:     'Tarek Eldin',
        passenger_gender:   'male',
        lat:                30.0245,
        lng:                31.4875,
        address:            '32 Al-Rehab St, New Cairo',
        pickup_time_offset: 2,
      },
    ],
    created_at:          '2026-05-04T10:00:00.000Z',
  },
];
