import type { DriverCycleSchedule } from '@/types/cycle';
import { computeUnlockAt } from '@/lib/tripUtils';

export const mockDriverCycleSchedule: DriverCycleSchedule = {
  cycle_id:         'cycle-001',
  status:           'active',
  cycle_start_date: '2026-05-17',
  cycle_end_date:   '2026-05-23',
  days: [
    // ── Saturday 17 May — completed ──────────────────────────────────────
    {
      date:      '2026-05-17',
      day_name:  'Saturday',
      day_short: 'Sat',
      is_today:  false,
      status:    'completed',
      runs: [
        {
          run_id:             'run-sat-01',
          departure_time:     '07:15',
          first_pickup_time:  '07:30',
          unlock_at:          computeUnlockAt('2026-05-17', '07:30'),
          estimated_end_time: '09:00',
          total_distance_km:  45.2,
          status:             'completed',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-001',
              passenger_name: 'Youssef M.', passenger_code: '8421',
              pickup_address: '15 El-Nasr St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0626, pickup_lng: 31.3417,
              scheduled_pickup: '07:30',
              dropoff_address: 'Future City, R5 District', dropoff_area: 'Future City',
              dropoff_lat: 30.0451, dropoff_lng: 31.7123,
              scheduled_dropoff: '08:15',
              pickup_status: 'picked_up', dropoff_status: 'dropped_off', chat_unlocked: true,
            },
            {
              stop_order: 2, passenger_id: 'u-002',
              passenger_name: 'Nour A.', passenger_code: '3756',
              pickup_address: '22 Hegaz St, Masr El Gedida', pickup_area: 'Masr El Gedida',
              pickup_lat: 30.0897, pickup_lng: 31.3222,
              scheduled_pickup: '07:45',
              dropoff_address: 'El Shrouk City, Sector 1', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1741, dropoff_lng: 31.6023,
              scheduled_dropoff: '08:30',
              pickup_status: 'picked_up', dropoff_status: 'dropped_off', chat_unlocked: true,
            },
            {
              stop_order: 3, passenger_id: 'u-003',
              passenger_name: 'Sara K.', passenger_code: '6193',
              pickup_address: 'Alf Maskn, Building 12', pickup_area: 'Alf Maskn',
              pickup_lat: 30.1200, pickup_lng: 31.4100,
              scheduled_pickup: '08:00',
              dropoff_address: '10th of Ramadan City, Industrial Zone', dropoff_area: '10th City',
              dropoff_lat: 30.2980, dropoff_lng: 31.7450,
              scheduled_dropoff: '09:00',
              pickup_status: 'picked_up', dropoff_status: 'dropped_off', chat_unlocked: true,
            },
          ],
        },
        {
          run_id:             'run-sat-02',
          departure_time:     '11:45',
          first_pickup_time:  '12:00',
          unlock_at:          computeUnlockAt('2026-05-17', '12:00'),
          estimated_end_time: '13:30',
          total_distance_km:  38.1,
          status:             'completed',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-004',
              passenger_name: 'Ahmed F.', passenger_code: '2918',
              pickup_address: '5 Makram Ebeid St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0580, pickup_lng: 31.3380,
              scheduled_pickup: '12:00',
              dropoff_address: 'Rehab City, Phase 1', dropoff_area: 'Rehab',
              dropoff_lat: 30.0581, dropoff_lng: 31.4942,
              scheduled_dropoff: '12:45',
              pickup_status: 'picked_up', dropoff_status: 'dropped_off', chat_unlocked: true,
            },
            {
              stop_order: 2, passenger_id: 'u-005',
              passenger_name: 'Mona S.', passenger_code: '7453',
              pickup_address: '8 Orouba St, Heliopolis', pickup_area: 'Heliopolis',
              pickup_lat: 30.0900, pickup_lng: 31.3200,
              scheduled_pickup: '12:15',
              dropoff_address: 'El Shrouk City, Gate 2', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1700, dropoff_lng: 31.5900,
              scheduled_dropoff: '13:00',
              pickup_status: 'picked_up', dropoff_status: 'dropped_off', chat_unlocked: true,
            },
            {
              stop_order: 3, passenger_id: 'u-006',
              passenger_name: 'Karim T.', passenger_code: '5382',
              pickup_address: 'Maadi, Road 9', pickup_area: 'Maadi',
              pickup_lat: 29.9620, pickup_lng: 31.2500,
              scheduled_pickup: '12:30',
              dropoff_address: 'Badr City, Block 7', dropoff_area: 'Badr City',
              dropoff_lat: 30.1300, dropoff_lng: 31.7200,
              scheduled_dropoff: '13:30',
              pickup_status: 'no_show', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
      ],
    },

    // ── Sunday 18 May — today ────────────────────────────────────────────
    {
      date:      '2026-05-18',
      day_name:  'Sunday',
      day_short: 'Sun',
      is_today:  true,
      status:    'active',
      runs: [
        {
          run_id:             'run-sun-01',
          departure_time:     '07:15',
          first_pickup_time:  '07:30',
          unlock_at:          computeUnlockAt('2026-05-18', '07:30'),
          estimated_end_time: '09:00',
          total_distance_km:  45.2,
          status:             'unlocked',  // change to 'locked' or 'active' to test
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-001',
              passenger_name: 'Youssef M.', passenger_code: '1847',
              pickup_address: '15 El-Nasr St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0626, pickup_lng: 31.3417,
              scheduled_pickup: '07:30',
              dropoff_address: 'Future City, R5 District', dropoff_area: 'Future City',
              dropoff_lat: 30.0451, dropoff_lng: 31.7123,
              scheduled_dropoff: '08:15',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-002',
              passenger_name: 'Nour A.', passenger_code: '9264',
              pickup_address: '22 Hegaz St, Masr El Gedida', pickup_area: 'Masr El Gedida',
              pickup_lat: 30.0897, pickup_lng: 31.3222,
              scheduled_pickup: '07:45',
              dropoff_address: 'El Shrouk City, Sector 1', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1741, dropoff_lng: 31.6023,
              scheduled_dropoff: '08:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-003',
              passenger_name: 'Sara K.', passenger_code: '4731',
              pickup_address: 'Alf Maskn, Building 12', pickup_area: 'Alf Maskn',
              pickup_lat: 30.1200, pickup_lng: 31.4100,
              scheduled_pickup: '08:00',
              dropoff_address: '10th of Ramadan City, Industrial Zone', dropoff_area: '10th City',
              dropoff_lat: 30.2980, dropoff_lng: 31.7450,
              scheduled_dropoff: '09:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
        {
          run_id:             'run-sun-02',
          departure_time:     '11:45',
          first_pickup_time:  '12:00',
          unlock_at:          computeUnlockAt('2026-05-18', '12:00'),
          estimated_end_time: '13:30',
          total_distance_km:  38.1,
          status:             'locked',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-004',
              passenger_name: 'Ahmed F.', passenger_code: '6039',
              pickup_address: '5 Makram Ebeid St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0580, pickup_lng: 31.3380,
              scheduled_pickup: '12:00',
              dropoff_address: 'Rehab City, Phase 1', dropoff_area: 'Rehab',
              dropoff_lat: 30.0581, dropoff_lng: 31.4942,
              scheduled_dropoff: '12:45',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-005',
              passenger_name: 'Mona S.', passenger_code: '8217',
              pickup_address: '8 Orouba St, Heliopolis', pickup_area: 'Heliopolis',
              pickup_lat: 30.0900, pickup_lng: 31.3200,
              scheduled_pickup: '12:15',
              dropoff_address: 'El Shrouk City, Gate 2', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1700, dropoff_lng: 31.5900,
              scheduled_dropoff: '13:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-006',
              passenger_name: 'Karim T.', passenger_code: '3594',
              pickup_address: 'Maadi, Road 9', pickup_area: 'Maadi',
              pickup_lat: 29.9620, pickup_lng: 31.2500,
              scheduled_pickup: '12:30',
              dropoff_address: 'Badr City, Block 7', dropoff_area: 'Badr City',
              dropoff_lat: 30.1300, dropoff_lng: 31.7200,
              scheduled_dropoff: '13:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
      ],
    },

    // ── Monday 19 May — upcoming ─────────────────────────────────────────
    {
      date:      '2026-05-19',
      day_name:  'Monday',
      day_short: 'Mon',
      is_today:  false,
      status:    'upcoming',
      runs: [
        {
          run_id:             'run-mon-01',
          departure_time:     '07:15',
          first_pickup_time:  '07:30',
          unlock_at:          computeUnlockAt('2026-05-19', '07:30'),
          estimated_end_time: '09:00',
          total_distance_km:  45.2,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-001',
              passenger_name: 'Youssef M.', passenger_code: '5312',
              pickup_address: '15 El-Nasr St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0626, pickup_lng: 31.3417,
              scheduled_pickup: '07:30',
              dropoff_address: 'Future City, R5 District', dropoff_area: 'Future City',
              dropoff_lat: 30.0451, dropoff_lng: 31.7123,
              scheduled_dropoff: '08:15',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-002',
              passenger_name: 'Nour A.', passenger_code: '7085',
              pickup_address: '22 Hegaz St, Masr El Gedida', pickup_area: 'Masr El Gedida',
              pickup_lat: 30.0897, pickup_lng: 31.3222,
              scheduled_pickup: '07:45',
              dropoff_address: 'El Shrouk City, Sector 1', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1741, dropoff_lng: 31.6023,
              scheduled_dropoff: '08:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-003',
              passenger_name: 'Sara K.', passenger_code: '2649',
              pickup_address: 'Alf Maskn, Building 12', pickup_area: 'Alf Maskn',
              pickup_lat: 30.1200, pickup_lng: 31.4100,
              scheduled_pickup: '08:00',
              dropoff_address: '10th of Ramadan City, Industrial Zone', dropoff_area: '10th City',
              dropoff_lat: 30.2980, dropoff_lng: 31.7450,
              scheduled_dropoff: '09:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
        {
          run_id:             'run-mon-02',
          departure_time:     '11:45',
          first_pickup_time:  '12:00',
          unlock_at:          computeUnlockAt('2026-05-19', '12:00'),
          estimated_end_time: '13:30',
          total_distance_km:  38.1,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-004',
              passenger_name: 'Ahmed F.', passenger_code: '9147',
              pickup_address: '5 Makram Ebeid St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0580, pickup_lng: 31.3380,
              scheduled_pickup: '12:00',
              dropoff_address: 'Rehab City, Phase 1', dropoff_area: 'Rehab',
              dropoff_lat: 30.0581, dropoff_lng: 31.4942,
              scheduled_dropoff: '12:45',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-005',
              passenger_name: 'Mona S.', passenger_code: '3826',
              pickup_address: '8 Orouba St, Heliopolis', pickup_area: 'Heliopolis',
              pickup_lat: 30.0900, pickup_lng: 31.3200,
              scheduled_pickup: '12:15',
              dropoff_address: 'El Shrouk City, Gate 2', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1700, dropoff_lng: 31.5900,
              scheduled_dropoff: '13:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-006',
              passenger_name: 'Karim T.', passenger_code: '6503',
              pickup_address: 'Maadi, Road 9', pickup_area: 'Maadi',
              pickup_lat: 29.9620, pickup_lng: 31.2500,
              scheduled_pickup: '12:30',
              dropoff_address: 'Badr City, Block 7', dropoff_area: 'Badr City',
              dropoff_lat: 30.1300, dropoff_lng: 31.7200,
              scheduled_dropoff: '13:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
      ],
    },

    // ── Tuesday 20 May — upcoming ────────────────────────────────────────
    {
      date:      '2026-05-20',
      day_name:  'Tuesday',
      day_short: 'Tue',
      is_today:  false,
      status:    'upcoming',
      runs: [
        {
          run_id:             'run-tue-01',
          departure_time:     '07:15',
          first_pickup_time:  '07:30',
          unlock_at:          computeUnlockAt('2026-05-20', '07:30'),
          estimated_end_time: '09:00',
          total_distance_km:  45.2,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-001',
              passenger_name: 'Youssef M.', passenger_code: '4790',
              pickup_address: '15 El-Nasr St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0626, pickup_lng: 31.3417,
              scheduled_pickup: '07:30',
              dropoff_address: 'Future City, R5 District', dropoff_area: 'Future City',
              dropoff_lat: 30.0451, dropoff_lng: 31.7123,
              scheduled_dropoff: '08:15',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-002',
              passenger_name: 'Nour A.', passenger_code: '1358',
              pickup_address: '22 Hegaz St, Masr El Gedida', pickup_area: 'Masr El Gedida',
              pickup_lat: 30.0897, pickup_lng: 31.3222,
              scheduled_pickup: '07:45',
              dropoff_address: 'El Shrouk City, Sector 1', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1741, dropoff_lng: 31.6023,
              scheduled_dropoff: '08:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-003',
              passenger_name: 'Sara K.', passenger_code: '8274',
              pickup_address: 'Alf Maskn, Building 12', pickup_area: 'Alf Maskn',
              pickup_lat: 30.1200, pickup_lng: 31.4100,
              scheduled_pickup: '08:00',
              dropoff_address: '10th of Ramadan City, Industrial Zone', dropoff_area: '10th City',
              dropoff_lat: 30.2980, dropoff_lng: 31.7450,
              scheduled_dropoff: '09:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
        {
          run_id:             'run-tue-02',
          departure_time:     '11:45',
          first_pickup_time:  '12:00',
          unlock_at:          computeUnlockAt('2026-05-20', '12:00'),
          estimated_end_time: '13:30',
          total_distance_km:  38.1,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-004',
              passenger_name: 'Ahmed F.', passenger_code: '5961',
              pickup_address: '5 Makram Ebeid St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0580, pickup_lng: 31.3380,
              scheduled_pickup: '12:00',
              dropoff_address: 'Rehab City, Phase 1', dropoff_area: 'Rehab',
              dropoff_lat: 30.0581, dropoff_lng: 31.4942,
              scheduled_dropoff: '12:45',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-005',
              passenger_name: 'Mona S.', passenger_code: '2437',
              pickup_address: '8 Orouba St, Heliopolis', pickup_area: 'Heliopolis',
              pickup_lat: 30.0900, pickup_lng: 31.3200,
              scheduled_pickup: '12:15',
              dropoff_address: 'El Shrouk City, Gate 2', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1700, dropoff_lng: 31.5900,
              scheduled_dropoff: '13:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-006',
              passenger_name: 'Karim T.', passenger_code: '7812',
              pickup_address: 'Maadi, Road 9', pickup_area: 'Maadi',
              pickup_lat: 29.9620, pickup_lng: 31.2500,
              scheduled_pickup: '12:30',
              dropoff_address: 'Badr City, Block 7', dropoff_area: 'Badr City',
              dropoff_lat: 30.1300, dropoff_lng: 31.7200,
              scheduled_dropoff: '13:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
      ],
    },

    // ── Wednesday 21 May — upcoming ──────────────────────────────────────
    {
      date:      '2026-05-21',
      day_name:  'Wednesday',
      day_short: 'Wed',
      is_today:  false,
      status:    'upcoming',
      runs: [
        {
          run_id:             'run-wed-01',
          departure_time:     '07:15',
          first_pickup_time:  '07:30',
          unlock_at:          computeUnlockAt('2026-05-21', '07:30'),
          estimated_end_time: '09:00',
          total_distance_km:  45.2,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-001',
              passenger_name: 'Youssef M.', passenger_code: '3069',
              pickup_address: '15 El-Nasr St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0626, pickup_lng: 31.3417,
              scheduled_pickup: '07:30',
              dropoff_address: 'Future City, R5 District', dropoff_area: 'Future City',
              dropoff_lat: 30.0451, dropoff_lng: 31.7123,
              scheduled_dropoff: '08:15',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-002',
              passenger_name: 'Nour A.', passenger_code: '6524',
              pickup_address: '22 Hegaz St, Masr El Gedida', pickup_area: 'Masr El Gedida',
              pickup_lat: 30.0897, pickup_lng: 31.3222,
              scheduled_pickup: '07:45',
              dropoff_address: 'El Shrouk City, Sector 1', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1741, dropoff_lng: 31.6023,
              scheduled_dropoff: '08:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-003',
              passenger_name: 'Sara K.', passenger_code: '9183',
              pickup_address: 'Alf Maskn, Building 12', pickup_area: 'Alf Maskn',
              pickup_lat: 30.1200, pickup_lng: 31.4100,
              scheduled_pickup: '08:00',
              dropoff_address: '10th of Ramadan City, Industrial Zone', dropoff_area: '10th City',
              dropoff_lat: 30.2980, dropoff_lng: 31.7450,
              scheduled_dropoff: '09:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
        {
          run_id:             'run-wed-02',
          departure_time:     '11:45',
          first_pickup_time:  '12:00',
          unlock_at:          computeUnlockAt('2026-05-21', '12:00'),
          estimated_end_time: '13:30',
          total_distance_km:  38.1,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-004',
              passenger_name: 'Ahmed F.', passenger_code: '4756',
              pickup_address: '5 Makram Ebeid St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0580, pickup_lng: 31.3380,
              scheduled_pickup: '12:00',
              dropoff_address: 'Rehab City, Phase 1', dropoff_area: 'Rehab',
              dropoff_lat: 30.0581, dropoff_lng: 31.4942,
              scheduled_dropoff: '12:45',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-005',
              passenger_name: 'Mona S.', passenger_code: '1293',
              pickup_address: '8 Orouba St, Heliopolis', pickup_area: 'Heliopolis',
              pickup_lat: 30.0900, pickup_lng: 31.3200,
              scheduled_pickup: '12:15',
              dropoff_address: 'El Shrouk City, Gate 2', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1700, dropoff_lng: 31.5900,
              scheduled_dropoff: '13:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-006',
              passenger_name: 'Karim T.', passenger_code: '8047',
              pickup_address: 'Maadi, Road 9', pickup_area: 'Maadi',
              pickup_lat: 29.9620, pickup_lng: 31.2500,
              scheduled_pickup: '12:30',
              dropoff_address: 'Badr City, Block 7', dropoff_area: 'Badr City',
              dropoff_lat: 30.1300, dropoff_lng: 31.7200,
              scheduled_dropoff: '13:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
      ],
    },

    // ── Thursday 22 May — upcoming ───────────────────────────────────────
    {
      date:      '2026-05-22',
      day_name:  'Thursday',
      day_short: 'Thu',
      is_today:  false,
      status:    'upcoming',
      runs: [
        {
          run_id:             'run-thu-01',
          departure_time:     '07:15',
          first_pickup_time:  '07:30',
          unlock_at:          computeUnlockAt('2026-05-22', '07:30'),
          estimated_end_time: '09:00',
          total_distance_km:  45.2,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-001',
              passenger_name: 'Youssef M.', passenger_code: '2718',
              pickup_address: '15 El-Nasr St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0626, pickup_lng: 31.3417,
              scheduled_pickup: '07:30',
              dropoff_address: 'Future City, R5 District', dropoff_area: 'Future City',
              dropoff_lat: 30.0451, dropoff_lng: 31.7123,
              scheduled_dropoff: '08:15',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-002',
              passenger_name: 'Nour A.', passenger_code: '5490',
              pickup_address: '22 Hegaz St, Masr El Gedida', pickup_area: 'Masr El Gedida',
              pickup_lat: 30.0897, pickup_lng: 31.3222,
              scheduled_pickup: '07:45',
              dropoff_address: 'El Shrouk City, Sector 1', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1741, dropoff_lng: 31.6023,
              scheduled_dropoff: '08:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-003',
              passenger_name: 'Sara K.', passenger_code: '1365',
              pickup_address: 'Alf Maskn, Building 12', pickup_area: 'Alf Maskn',
              pickup_lat: 30.1200, pickup_lng: 31.4100,
              scheduled_pickup: '08:00',
              dropoff_address: '10th of Ramadan City, Industrial Zone', dropoff_area: '10th City',
              dropoff_lat: 30.2980, dropoff_lng: 31.7450,
              scheduled_dropoff: '09:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
        {
          run_id:             'run-thu-02',
          departure_time:     '11:45',
          first_pickup_time:  '12:00',
          unlock_at:          computeUnlockAt('2026-05-22', '12:00'),
          estimated_end_time: '13:30',
          total_distance_km:  38.1,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-004',
              passenger_name: 'Ahmed F.', passenger_code: '7634',
              pickup_address: '5 Makram Ebeid St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0580, pickup_lng: 31.3380,
              scheduled_pickup: '12:00',
              dropoff_address: 'Rehab City, Phase 1', dropoff_area: 'Rehab',
              dropoff_lat: 30.0581, dropoff_lng: 31.4942,
              scheduled_dropoff: '12:45',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-005',
              passenger_name: 'Mona S.', passenger_code: '9021',
              pickup_address: '8 Orouba St, Heliopolis', pickup_area: 'Heliopolis',
              pickup_lat: 30.0900, pickup_lng: 31.3200,
              scheduled_pickup: '12:15',
              dropoff_address: 'El Shrouk City, Gate 2', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1700, dropoff_lng: 31.5900,
              scheduled_dropoff: '13:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-006',
              passenger_name: 'Karim T.', passenger_code: '3482',
              pickup_address: 'Maadi, Road 9', pickup_area: 'Maadi',
              pickup_lat: 29.9620, pickup_lng: 31.2500,
              scheduled_pickup: '12:30',
              dropoff_address: 'Badr City, Block 7', dropoff_area: 'Badr City',
              dropoff_lat: 30.1300, dropoff_lng: 31.7200,
              scheduled_dropoff: '13:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
      ],
    },

    // ── Friday 23 May — upcoming ─────────────────────────────────────────
    {
      date:      '2026-05-23',
      day_name:  'Friday',
      day_short: 'Fri',
      is_today:  false,
      status:    'upcoming',
      runs: [
        {
          run_id:             'run-fri-01',
          departure_time:     '07:15',
          first_pickup_time:  '07:30',
          unlock_at:          computeUnlockAt('2026-05-23', '07:30'),
          estimated_end_time: '09:00',
          total_distance_km:  45.2,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-001',
              passenger_name: 'Youssef M.', passenger_code: '6840',
              pickup_address: '15 El-Nasr St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0626, pickup_lng: 31.3417,
              scheduled_pickup: '07:30',
              dropoff_address: 'Future City, R5 District', dropoff_area: 'Future City',
              dropoff_lat: 30.0451, dropoff_lng: 31.7123,
              scheduled_dropoff: '08:15',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-002',
              passenger_name: 'Nour A.', passenger_code: '3175',
              pickup_address: '22 Hegaz St, Masr El Gedida', pickup_area: 'Masr El Gedida',
              pickup_lat: 30.0897, pickup_lng: 31.3222,
              scheduled_pickup: '07:45',
              dropoff_address: 'El Shrouk City, Sector 1', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1741, dropoff_lng: 31.6023,
              scheduled_dropoff: '08:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-003',
              passenger_name: 'Sara K.', passenger_code: '5927',
              pickup_address: 'Alf Maskn, Building 12', pickup_area: 'Alf Maskn',
              pickup_lat: 30.1200, pickup_lng: 31.4100,
              scheduled_pickup: '08:00',
              dropoff_address: '10th of Ramadan City, Industrial Zone', dropoff_area: '10th City',
              dropoff_lat: 30.2980, dropoff_lng: 31.7450,
              scheduled_dropoff: '09:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
        {
          run_id:             'run-fri-02',
          departure_time:     '11:45',
          first_pickup_time:  '12:00',
          unlock_at:          computeUnlockAt('2026-05-23', '12:00'),
          estimated_end_time: '13:30',
          total_distance_km:  38.1,
          status:             'upcoming',
          passengers: [
            {
              stop_order: 1, passenger_id: 'u-004',
              passenger_name: 'Ahmed F.', passenger_code: '8563',
              pickup_address: '5 Makram Ebeid St, Nasr City', pickup_area: 'Nasr City',
              pickup_lat: 30.0580, pickup_lng: 31.3380,
              scheduled_pickup: '12:00',
              dropoff_address: 'Rehab City, Phase 1', dropoff_area: 'Rehab',
              dropoff_lat: 30.0581, dropoff_lng: 31.4942,
              scheduled_dropoff: '12:45',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 2, passenger_id: 'u-005',
              passenger_name: 'Mona S.', passenger_code: '2094',
              pickup_address: '8 Orouba St, Heliopolis', pickup_area: 'Heliopolis',
              pickup_lat: 30.0900, pickup_lng: 31.3200,
              scheduled_pickup: '12:15',
              dropoff_address: 'El Shrouk City, Gate 2', dropoff_area: 'El Shrouk',
              dropoff_lat: 30.1700, dropoff_lng: 31.5900,
              scheduled_dropoff: '13:00',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
            {
              stop_order: 3, passenger_id: 'u-006',
              passenger_name: 'Karim T.', passenger_code: '7418',
              pickup_address: 'Maadi, Road 9', pickup_area: 'Maadi',
              pickup_lat: 29.9620, pickup_lng: 31.2500,
              scheduled_pickup: '12:30',
              dropoff_address: 'Badr City, Block 7', dropoff_area: 'Badr City',
              dropoff_lat: 30.1300, dropoff_lng: 31.7200,
              scheduled_dropoff: '13:30',
              pickup_status: 'pending', dropoff_status: 'pending', chat_unlocked: false,
            },
          ],
        },
      ],
    },
  ],
};
